services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: table_assistant_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
